#+title: Nietzsche Dan Kierkegaard : Lamaran Ditolak Dua Kali Eropa Ku Kuasai
#+author: Aziz Amerul Faozi

* Pengantar
Socrates pernah berujar, "Jatuh Cintalah jika ternyata anda mencintai wanita
yang salah anda akan menjadi filsuf." Apakah ini juga yang membuat Kierkegaard
dan Nietzsche tidak ragu dalam mencintai? Dari beberapa tulisan Kierkegaard
dia memang sangat menyukai pandangan pandangan dari Sokrates. Kierkegaard
menyetujui bahwa kebenaran dimiliki oleh tiap tiap individu, kebeneran yang
bersifat partikular, diskusi yang dilakukan oleh Sokrates untuk membuat tiap
individu ada dalam kesadaran pertikular ini dia gunakan untuk mengkritik para
filsuf seangkatannya yaitu Imanuel Kant dan George Wilhelm Fredrich Hegel.

* Revolusi Metafisika Kierkegaard
Baik Hegel dan Kant ingin menunjukan bahwa ada kebenaran diluar individu yang
bersifat mutlak. Hegel mengatakan bahwa adanya kesadaran Absolute diluar diri
manusia, artinya ada kebenaran yang diluar inidividu yang membangun sebuah
sejarah. Sedangkan Kant mengatakan bahwa apa yang kita lihat belum tentu
makna itu sesungguhnya, setiap entitas sebenernya ada kebenaran konkretnya
namun hal itu terkadang berubah penafsiran bagi para pengamat. Kebenaran yang
ontologis yang dikemukakan oleh Hegel dan Kant membuat Kierkegaard tidak puas
dengan jawaban mereka. 

Kierkegaard berujar bahwa hanya yang mengalami kondisi eksistensiallah yang
tahu kebenaran itu sendiri. Mungkin bagi Kant payung sebenernya bukanlah payung,
bagi Hegel ada sebuah gagasan absolute tentang payung selain dari apa yang tiap
manusia nikmati sebagai payung, tapi bagi Kierkegaard yang tahu makna payung
adalah pengguna payung itu sendiri, payung bisa berarti sebuah alat peneduh
hujan dan itu benar bagi yang menggunakan, payung bisa jadi emas kawin untuk
orang yang menggunakan alat itu sebagai emas kawin, pada akhirnya ada banyak
macam kebeneran dari payung itu sendiri. Kebeneran bukan sebuah gagasan omong
kosong seperti ungkapan Hegel dan Kant tapi sesuatu yang nyata tersingkap
bagi orang yang eksis didalamnya.

* Gagasan Hegel dan Kant omong Kosong
Kebenaran yang berada diluar eksistensi adalah omong kosong bagi Kierkegaard.
Kebenaran bahwa Payung adalah sebuah emas kawin hanyalah omong kosong bagi
seorang anak kecil yang tidak menikah dan kedinginan ditengah hujan. Ide tentang
adanya Roh Absolute tidak pernah terwujud untuk tiap individu karena kebenaran
yang bermakna hanya bisa terjadi saat-saat kondisi eksistensial.

* Kebenaran Seperti Wanita, Nietzsche
Ketika seorang para pemuda di Mesir melihat orang disana sedang menyembah
sebuah patung para pemuda itu kemudian terpikirkan untuk membedah sesembahan
itu, setelah itu dia menyadari bahwa dia tidak mendapatkan apapun dari sana.
Kebenaran seperti Wanita, untuk bisa mendapatkannya kita perlu menyelami
kesadaran tertentu, tapi ketika kita menelanjangi kebenaran maka kita
akan di cap tidak sopan dan mendapatkan penderitaan dari kebenaran itu.
Kebenaran seperti wanita ini yang ingin dijelaskan oleh Nietzsche bahwa ketika
kita mencari kebenaran yang kita dapatkan adalah sebuah paradox.
* Quotes
* Serba Salah, Kierkegaard - Either/Or
Hidup salah mati juga salah, semua serba salah.
* The Works of Love, Kierkegaard
Cinta adalah kecemasan eksistensial terbesar manusia.

