#+title: Sejarah Pembangunan Kesehatan Indonesia 1973 - 2009
#+author: Aziz Amerul Faozi

* Pengantar
Membaca Sejarah Pembangunan Kesehatan Indonesia 1973 - 2009 karya Kementrian
Kesehatan yang terbit pada tahun 2011 kita akan mengenal beragam kebijakan-
kebijakan dari menteri yang pernah menjabat di kementrian kesehatan Indonesia.

* Prof Dr. Gerritz Siwabessy
Pak Gerritz adalah menteri yang paling lama menjabat di kementrian kesehatan
republik Indonesia. Pak Gerritz berasal dari Maluku, memulai karir menjadi menteri
dari tahun 1966 hingga 1978. Salah satu pencapainnya adalah membersihkan PKI
dari kementrian kesehatan, Siwabessy membangun kembali hubungan dengan PBB,
menangani penyakit menular seperti SEP dan kemudian penyakit cacar. Dalam
pemerintahannya dia mengikuti pelita 1 dan 2 dan dalam repelita 2 dia melaksanakan
program pemberantasan penyakit menular.
Seperti diketahui pelita 1 belum mendapatkan perhatian pembangunan dari pemerintah
di bidang kesehatan, kemudian di pelita 2 bayak pembangunan guna mencapai
jumlah tenaga pelayanan kesehatan dan keluarnya inpress.

* DR Sewardjono Soerjajaningrat (1978-1983)
Dalam pemerintahnnya kita juga mengenal tentang KB dan imunisasi,
ini terjadi pada repelita 3. Beliau berasal dari Purwodadi. Dia seorang perwira
angkatan darat, tetapi dia lulus dari fakultas kedokteran. Kasus yang dihadapi
dalam pemerintahan Soewarjono suryadiningrat adalah angka kematian dari
bayi yang tinggi, maka dari itu program KB dianggapnya sebagai solusi, dan
memang terbukti angka kematiannya menjadi turun.

Kalian mungkin mengenal garam beriodium, kasus anak gunung yang kurang iodium
juga menjadi topik kebijakan yang dianutnya, dalam kasus penyakit yang dihadapi
dari pemerintahannya adalah penyakit kulit, tipus, penyakit cacing dan penyakit
miskin lainnya. Pembangunan kesehatannya juga ditujukan dengan pembangunan untuk
para manusia miskin. Dijamannya dikenal juga sebutan UKS.

* DR Sewardjono Soerjajaningrat (1983-1988)
Dalam periode keduanya, ada permasalahan dimana pendidikan di Indonesia masih
rendah maka dari itu perlu diadakan penyuluhan untuk memberitahu bahwa
kebijakan yang dilakukan oleh kementrian kesehatan adalah untuk kepentingan
mereka. Di masa ini Soewardjono Soerjaningrat meminta untuk diberlakukan
pelarangan rokok, tapi waktu itu dia meminta pak Soeharto yang sedang merokok
cerutu, dan membalas, "Saya tidak ingin menghilangkan pendapatan petani
tembakau". Di era ini Soewarjono juga membuat posyandu.

Didalam Repelita 4, ada rencana pembangunan rumah sakit umum dan rumah sakit
khusus, baik pemerintah maupun swasta. Kemudian adanya pendidikan dan pelatihan
tenaga kesehatan. Dan dalam Pelita 4 drajat kesehatan makin meningkat dilihat
dari angka kelahiran, kematian, kesakitan, dan status gizi. Terbentuknya PMKD
Pembangunan kesehatan masyarakat desa. Lahirnya mars hidup sehat, halaman 175.


* Dr, Adhyatama
Membersihan Departmen Dari Korupsi, Alumni UI.
Muncul penyakit orang kaya, kardiovaskuler, degeneratif,
kanker, pms.
Di sini dibuat puskesmas dengan fasilitas perawatan. Disini tidak hanya masyarakat
desa yang menjadi sasaran pembangunan tapi juga masyarakat kota. Hasilnya
perubahan undang undang. Di jaman ini juga mulai dikembangkan penelitian
dibidang alat kesehatan. Kemudian adanya pemerataan tenaga kesehatan, munculnya
obat generik. Munculnya JPKM. Beliau hidup dalam pelita 5, dalam pelita 5
penyediaan air bersih menjadi topik utama.

* DR Sujudi
Orang bogor, anak FKUI, sebelumnya menjadi Dosen DI FKUI dia mengepalai
mikrobioligi sejak tahun 1966. Mendapatkan pengakuan internasional setelah
disertasinya tentang Identifikasi Mikrobiologi. Dalam pelita 6, pembangunan
diarahkan untuk meningkatkan kualitas dan pemerataan jangkauan pelayanan
kesehatan dan perbaikan Gizi. Dalam pelita 5 angka prevalensi kurang protein
menurun 18.9 persen  pada 1978 dan 11,8 persen pada 1992. Pada pelita 1
jumlah puskesmas 1227 dan diakhiri 2343 puskesmas.
Kebijakan pembangunan beliau adalah mendorong peran serta masyarakat dan
dunia usaha. Artinya kemisikin perlu diatasi dengan usaha, karena akan
menentukan kualitas kesehatan. Karena munculnya permukiman kumuh di perkotaan,
maka topik ini menjadi perhatian. Dalam pemerintahannya kemampuan POM meningkat.
Dalam pemerintahannya juga mengankat topik pengobatan tradisional.
Dalam masa sujudi muncul pekan imunisasi Nasional untuk mengatasi polio

* DR Farid Anfasa Muluk
Dia mengenalkan e-mail sehingga disebut bapak email dari Depkes, dia anak
FKUI. Karena RRC berhasil membuat obat sendiri untuk mengurangi ketergantungan
pada pembuatan obat asing maka dia menirunya, dari sini dia mengusulkan WKS
Wajib Kerja Sarjana kemudian didemo oleh mahasiswanya sendiri. Farid Anfasa
mengajukan tentang paradigma sehat. Dijaman dia banyak konflik yang terjadi
semisal konflik Kalimantan, konflik NAD, Konfli NTT, konflik maluku, dampaknya
faskes menjadi tidak tertangani dengan baik di daerah tersebut.

* Dr Achmad Sujudi
Dia anak FKUI dan pernah WKS di pulau Buru di kamp tahanan politik G30SPKI
Achmad Sujudi pernah sekolah di Jhon Hopkins Hospital. Di zamannya muncul
Gerdunas, Gerakan terpadu nasional untuk menangani tuberkolosis, Gerbak Malaria,
JPS BK, seperti revitalisasi Posyandu , pemberian makanan pada balita,

* Siti Fadilah Supari
Anak FK UGM dan FKUI, dalam pemerintahannya ada beberapa kasus seperti kasus kapal induk
penelitian amerika yang ada di Indonesia tapi tidak berguna akhirnya dengan
autoritasnya sebagai menteri berhasil diusir. Adanya kasus korupsi askes kin
dimana orang membeli obat yang mahal tapi tidak diberikan kepada penderita malah
dijual lagi ke produsen (solved), kemudian kasus CEO Microsoft Bill Gates pada
kasus flu burung. Kejadian bencana alam di NAD
